args = {
    'adduct': {"name": "adduct", "short":'add', "defult":"M+H"},
    'USI1': {"name": "USI1", "short":'USI1', "defult":""},
    'USI2': {"name": "USI2", "short":'USI2', "defult":""},
    'SMILES1': {"name": "SMILES1", "short":'SMILES1', "defult":""}, 
    'SMILES2': {"name": "SMILES2", "short":'SMILES2', "defult":""},
    'mz_tolerance': {"name": "mz_tolerance", "short":'mz', "defult":0.05},
    'ppm': {"name": "ppm", "short":'ppm', "defult":40},
    'filter_peaks_method': {"name": "filter_peaks_method", "short":'filter', "defult":"intensity"},
    'filter_peaks_variable': {"name": "filter_peaks_variable", "short":'filter_var', "defult":0.01},
    'presence_only': {"name": "presence_only", "short":'presence', "defult":False},
    'consider_intensity': {"name": "consider_intensity", "short":'intensity', "defult":True},
    'shifted_only': {"name": "shifted_only", "short":'shifted', "defult":False},
    'USIhelp': {"name": "USIhelp", "short":'USIhelp', "defult":None},
    'SMILEShelp': {"name": "SMILEShelp", "short":'SMILEShelp', "defult":None},
}