args = {
    'adduct': {"name": "adduct", "short":'add', "defult":"M+H"},
    'USI1': {"name": "USI1", "short":'USI1', "defult":"mzspec:GNPS:BERKELEY-LAB:accession:CCMSLIB00010105317"},
    'USI2': {"name": "USI2", "short":'USI2', "defult":"mzspec:GNPS:BERKELEY-LAB:accession:CCMSLIB00010117740"},
    'SMILES1': {"name": "SMILES1", "short":'SMILES1', "defult":"COc1ccc(-c2coc3cc(OC)c(OC)cc3c2=O)cc1"}, 
    'SMILES2': {"name": "SMILES2", "short":'SMILES2', "defult":"COc1ccc(-c2coc3cc(OC)c(OC)cc3c2=O)cc1OC"},
    'mz_tolerance': {"name": "mz_tolerance", "short":'mz', "defult":0.05},
    'ppm': {"name": "ppm", "short":'ppm', "defult":1.01},
    'filter_peaks_method': {"name": "filter_peaks_method", "short":'filter', "defult":"top_k"},
    'filter_peaks_variable': {"name": "filter_peaks_variable", "short":'filter_var', "defult":50},
    'presence_only': {"name": "presence_only", "short":'presence', "defult":False},
    'consider_intensity': {"name": "consider_intensity", "short":'intensity', "defult":True},
    'shifted_only': {"name": "shifted_only", "short":'shifted', "defult":False},
    'USIhelp': {"name": "USIhelp", "short":'USIhelp', "defult":None},
    'SMILEShelp': {"name": "SMILEShelp", "short":'SMILEShelp', "defult":None},
}