channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - rdkit
  - requests
  - xlsxwriter
  - prettytable
  - dash
  - numpy
  - pip
  - pip:
    - cairosvg
    - tqdm
    - IPython
    - furl
    - dash_daq
    - dash-bootstrap-components
    - pillow
    - openpyxl
    - openpyxl-image-loader
    