name: modi-finder-analysis

channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.16
  - rdkit=2023.03.1
  - requests=2.29.0
  - xlsxwriter=3.1.0
  - prettytable=3.7.0
  - numpy=1.24.3
  - pip=23.1.2
  - pillow=9.4.0
  - pandas=1.5.3
  - ipykernel=6.21.3
  - pip:
    - cairosvg==2.7.0
    - tqdm==4.65.0
    - ipython==8.13.2
    - msbuddy==0.2.3
    - openpyxl==3.1.2
    - openpyxl-image-loader==1.0.5
    - scipy==1.11.3
    - seaborn==0.13.0
    - Jinja2==3.1.3
    - IPython