version: '3'
services:
  template-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template-dash
    volumes:
      - ./logs:/app/logs:rw
    ports:
    - "8081:8081"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: template.ucsd.edu
      VIRTUAL_PORT: 8081
      LETSENCRYPT_HOST: template.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu


networks:
  nginx-net:
    external:
      name: nginx-net
